### ISSUE TITLE
Meaningful unit test coverage - Page 

### ISSUE THREAD

**Issue by rellison192** [wayfair/awesome-learning#118]
## Problem
As part of issue #59, all snapshots tests where removed. We would now like to replace these snapshots with a more meaningful unit test.

## Acceptance Criteria

Using @testing-library/react create a test for `Page.js` found in `src/components/Page/`

**Comment by nicolabuckhurst** [comment]
I would like to look at this issue

**Comment by laura-barluzzi** [comment]
@rellison192 hey there! I'm working on this task and I have a clarification question for adding better unit tests.

I did the tests for these scenarios:

1. No props
2. props.title

But could you clarify what `children` should be? I never see it in use in the code.

**Comment by laura-barluzzi** [comment]
@nicolabuckhurst ooops, I've been working on this already. Do you mind picking another component to test?

**Comment by SheaBelsky** [comment]
@nicolabuckhurst Since @laura-barluzzi has already started on this issue and since I've already assigned you a different issue, I've assigned it to Laura.

Laura, `children` refers to the children of this React Component. For example:

```
<Layout title={pageTitle} description={siteSubtitle}>
    <Page>
      <Courses edges={edges} />
      <Pagination
        prevPagePath={prevPagePath}
        nextPagePath={nextPagePath}
        hasPrevPage={hasPrevPage}
        hasNextPage={hasNextPage}
      />
    </Page>
</Layout>
```

The children would refer to the Courses and Pagination elements. For PropTypes, you'd want `PropTypes.node.isRequired` to indicate that a React node should be passed as this prop.
